name: movie_app
description: for takehometest
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0-146.2.beta <3.0.0"

dependencies:
  #Networdk
  dio: ^4.0.6
  url_launcher: ^6.1.8
  #networklogger
  pretty_dio_logger: ^1.2.0-beta-1
  #UI-plugins
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  readmore: ^2.2.0
  shimmer: ^2.0.0
  fluttertoast: ^8.2.2
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^4.0.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  #StateManagement
  flutter_bloc: ^8.1.1
  #Routing
  get_it: ^7.2.0
  go_router: ^6.0.9
  #localstoragee
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/ic_launcher.png"
  image_path_ios: "assets/images/ic_launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/ic_launcher.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/ic_launcher.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true