name: movie_app
description: for takehometest
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0-146.2.beta <3.0.0"

dependencies:
  #Networdk
  dio: ^4.0.6
  url_launcher: ^6.1.8
  #networklogger
  pretty_dio_logger: ^1.2.0-beta-1
  #UI-plugins
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  readmore: ^2.2.0
  shimmer: ^2.0.0

  dartz: ^0.10.1
  equatable: ^2.0.5
  #StateManagement
  flutter_bloc: ^8.1.1

  get_it: ^7.2.0
  go_router: ^6.0.9
  google_fonts: ^4.0.1
  #localstoragee
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12
  stream_transform: ^2.1.0

  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true

